// Builds the overlay stylesheet: design tokens retargeted at the shadow host, plus Tailwind utilities.
// Output is embedded as a string (src/css.generated.ts) so the overlay is one script with no extra requests.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
mkdirSync(path.join(root, "dist"), { recursive: true });
const bin = path.join(root, "node_modules/.bin/tailwindcss");
execFileSync(bin, ["-i", path.join(root, "src/overlay.css"), "-o", path.join(root, "dist/tw.css"), "--minify"], { stdio: "inherit", cwd: root });
const tokens = readFileSync(path.join(root, "../../design/tokens.css"), "utf8")
  .replace(/:root:not\(\[data-theme="light"\]\)/g, ':host(:not([data-theme="light"]))')
  .replace(/:root\[data-theme="(light|dark)"\]/g, ':host([data-theme="$1"])')
  .replace(/:root/g, ":host");
const base = `:host{all:initial;position:fixed;inset:0;pointer-events:none;z-index:2147483647;font:14px/1.5 var(--font-ui);color:var(--text);-webkit-font-smoothing:antialiased}*{box-sizing:border-box}`;
const tw = readFileSync(path.join(root, "dist/tw.css"), "utf8");
// Tailwind v4 declares its internal variables (--tw-translate-x, --tw-border-style, shadow parts...) with @property,
// which does NOT apply inside a shadow root: transforms, borders and shadows would silently compute to "none".
// Re-declare every initial value as a plain custom property on the host.
const props = [...tw.matchAll(/@property\s+(--tw-[\w-]+)\s*\{([^}]*)\}/g)]
  .map(([, name, body]) => { const m = /initial-value:\s*([^;}]*)/.exec(body); return m ? `${name}:${m[1].trim()}` : null; })
  .filter(Boolean);
const css = tokens + "\n" + base + "\n@keyframes recast-bar{from{transform:scaleX(1)}to{transform:scaleX(0)}}\n" + `:host{${props.join(";")}}\n` + tw;
console.log(`re-declared ${props.length} Tailwind @property defaults on :host`);
writeFileSync(path.join(root, "dist/overlay.css"), css);
writeFileSync(path.join(root, "src/css.generated.ts"), `// GENERATED by scripts/build-css.mjs. Do not edit.\nexport const OVERLAY_CSS = ${JSON.stringify(css)};\n`);
console.log(`overlay css: ${(css.length / 1024).toFixed(1)} KB`);
