// Generates, from the JSON Schemas (the source of truth):
//   packages/core/src/generated/types.ts       TypeScript types
//   packages/core/src/generated/validators.js  Ajv *standalone* validators
// Standalone matters: MV3 extension pages forbid eval / new Function, and Ajv's
// default compile() uses new Function. Precompiled validators avoid that.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.resolve(root, "../packages/core/src/generated");
mkdirSync(out, { recursive: true });
const rd = (p) => JSON.parse(readFileSync(path.join(root, p), "utf8"));
const list = (d) => readdirSync(path.join(root, d)).filter((f) => f.endsWith(".schema.json")).map((f) => `${d}/${f}`);

const schemaFiles = [...list("common"), ...list("objects"), ...list("contracts"), "grammar/relations.schema.json"];
const schemas = schemaFiles.map(rd);

// ---- validators (standalone) ----
const ajv = new Ajv2020({ schemas, allErrors: true, strict: true, strictRequired: false, code: { source: true, esm: true } });
const ID = (f) => rd(f).$id;
const exportsMap = {
  validateEnvelope: ID("common/envelope.schema.json"),
  validateCandidate: ID("common/candidate.schema.json"),
  validateContract: ID("contracts/capability.schema.json"),
  validateRelations: ID("grammar/relations.schema.json"),
};
let code = standaloneCode(ajv, exportsMap);
writeFileSync(path.join(out, "validators.js"), "// GENERATED by schema/scripts/build.mjs. Do not edit.\n" + code);

writeFileSync(path.join(out, "validators.d.ts"),
  "// GENERATED by schema/scripts/build.mjs. Do not edit.\n" +
  Object.keys(exportsMap).map((n) => `export const ${n}: ((data: unknown) => boolean) & { errors?: { instancePath: string; message?: string }[] | null };`).join("\n") + "\n");

// ---- types ----
const opts = { cwd: root + "/", bannerComment: "", additionalProperties: false, unreachableDefinitions: false, $refOptions: { resolve: { http: false } } };
let ts = "// GENERATED by schema/scripts/build.mjs. Do not edit.\n/* eslint-disable */\n";
for (const f of ["objects/person", "objects/document", "objects/event", "objects/location", "objects/image", "objects/message", "objects/task", "objects/product", "objects/research-paper", "common/evidence", "common/provenance", "contracts/capability"]) {
  ts += await compile(rd(`${f}.schema.json`), path.basename(f), { ...opts, cwd: path.join(root, path.dirname(f)) + "/" });
}
writeFileSync(path.join(out, "types.ts"), ts);
console.log("generated validators.js and types.ts");
